GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJpd2FuIHB1cndhZGkiLCJlbWFpbCI6ImVtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTY1NjIzNTIxMCwiZXhwIjoxNjU2MjM1MjMwfQ.MM6aToEycAL29xAxuamKi6u673u9IUBlU9ezT9X02DA

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "iwan purwadi",
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout